#############################################################################
# Makefile for building: mario_world.app/Contents/MacOS/mario_world
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  mario_world.pro
# Template: app
# Command: /Users/jeffeehsiung/Qt/6.5.3/macos/bin/qmake -o Makefile mario_world.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtGui.framework/Headers -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang -F/Users/jeffeehsiung/Qt/6.5.3/macos/lib
QMAKE         = /Users/jeffeehsiung/Qt/6.5.3/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/jeffeehsiung/Qt/6.5.3/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/jeffeehsiung/Qt/6.5.3/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mario_world1.0.0
DISTDIR = /Users/jeffeehsiung/Desktop/Toledo/advance\ programming/lab/mario_world/.tmp/mario_world1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/jeffeehsiung/Qt/6.5.3/macos/lib
LIBS          = $(SUBLIBS) -F/Users/jeffeehsiung/Qt/6.5.3/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_qmake_qmake_qm_files.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_qmake_qmake_qm_files.o \
		moc_mainwindow.o
DIST          = /Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/device_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/unix.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/macx.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/sanitize.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang-mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/qconfig.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_functions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/toolchain.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resolve_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lrelease.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qml_debug.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/mac.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/warn_on.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/permissions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources_functions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/moc.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/uic.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/thread.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qmake_use.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/file_copies.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/rez.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exceptions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/yacc.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lex.prf \
		mario_world.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = mario_world
DESTDIR       = 
TARGET        = mario_world.app/Contents/MacOS/mario_world

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/jeffeehsiung/Desktop/Toledo/advance programming/lab/mario_world/mario_world.pro


include /Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

mario_world.app/Contents/MacOS/mario_world: ui_mainwindow.h $(OBJECTS)  
	@test -d mario_world.app/Contents/MacOS/ || mkdir -p mario_world.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mario_world.pro /Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf /Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/device_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/unix.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/macx.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/sanitize.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang-mac.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/qconfig.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_functions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/toolchain.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resolve_config.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lrelease.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qml_debug.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/mac.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/warn_on.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/permissions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources_functions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/moc.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/uic.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/thread.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qmake_use.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/file_copies.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/rez.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exceptions.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/yacc.prf \
		/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lex.prf \
		mario_world.pro \
		qmake_qmake_qm_files.qrc \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile mario_world.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_pre.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/device_config.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/unix.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/mac.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/macx.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/sanitize.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/common/clang-mac.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/qconfig.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_functions.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt_config.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/spec_post.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/toolchain.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_pre.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resolve_config.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/default_post.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lrelease.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qml_debug.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/mac.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/warn_on.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/permissions.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qt.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources_functions.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/resources.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/moc.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/uic.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/unix/thread.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/qmake_use.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/file_copies.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/rez.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/exceptions.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/yacc.prf:
/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/features/lex.prf:
mario_world.pro:
qmake_qmake_qm_files.qrc:
/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mario_world.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

mario_world.app/Contents/PkgInfo: 
	@test -d mario_world.app/Contents || mkdir -p mario_world.app/Contents
	@$(DEL_FILE) mario_world.app/Contents/PkgInfo
	@echo "APPL????" > mario_world.app/Contents/PkgInfo
mario_world.app/Contents/Info.plist: 
	@test -d mario_world.app/Contents || mkdir -p mario_world.app/Contents
	@$(DEL_FILE) mario_world.app/Contents/Info.plist
	@plutil -convert xml1 -o - /Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,JW.mario-world,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},JW.mario-world,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,mario_world,g" -e "s,@LIBRARY@,mario_world,g" -e "s,\$${EXECUTABLE_NAME},mario_world,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >mario_world.app/Contents/Info.plist

all: Makefile \
		mario_world.app/Contents/PkgInfo \
		mario_world.app/Contents/Info.plist mario_world.app/Contents/MacOS/mario_world

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mario_world_en_US.ts $(DISTDIR)/
	$(COPY_FILE) --parents qmake_qmake_qm_files.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/
	$(COPY_FILE) --parents mario_world_en_US.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mario_world.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_lrelease_make_all: .qm/mario_world_en_US.qm
compiler_lrelease_clean:
	-$(DEL_FILE) .qm/mario_world_en_US.qm
.qm/mario_world_en_US.qm: mario_world_en_US.ts
	/Users/jeffeehsiung/Qt/6.5.3/macos/bin/lrelease mario_world_en_US.ts -qm .qm/mario_world_en_US.qm

compiler_rcc_make_all: qrc_qmake_qmake_qm_files.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qmake_qmake_qm_files.cpp
qrc_qmake_qmake_qm_files.cpp: qmake_qmake_qm_files.qrc \
		/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/rcc \
		.qm/mario_world_en_US.qm
	/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/rcc -name qmake_qmake_qm_files --no-zstd qmake_qmake_qm_files.qrc -o qrc_qmake_qmake_qm_files.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/moc
	/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=15 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/jeffeehsiung/Qt/6.5.3/macos/mkspecs/macx-clang -I'/Users/jeffeehsiung/Desktop/Toledo/advance programming/lab/mario_world' -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtGui.framework/Headers -I/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/jeffeehsiung/Qt/6.5.3/macos/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/uic
	/Users/jeffeehsiung/Qt/6.5.3/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_lrelease_clean compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers/QLocale \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers/qlocale.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers/QTranslator \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtCore.framework/Headers/qtranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/jeffeehsiung/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_qmake_qmake_qm_files.o: qrc_qmake_qmake_qm_files.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_qmake_qm_files.o qrc_qmake_qmake_qm_files.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/mario_world/bin || mkdir -p $(INSTALL_ROOT)/opt/mario_world/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/mario_world/bin/mario_world.app
	
	$(QINSTALL) mario_world.app $(INSTALL_ROOT)/opt/mario_world/bin/mario_world.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/mario_world/bin/mario_world.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/mario_world/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

