# iOS Simulator Toolchain for CMake
# Targets the Xcode iOS Simulator (x86_64 + arm64 for Apple Silicon Macs)

set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64" CACHE STRING "Simulator architectures")
set(CMAKE_OSX_DEPLOYMENT_TARGET "15.0" CACHE STRING "Minimum iOS deployment target")
set(CMAKE_OSX_SYSROOT "iphonesimulator" CACHE STRING "iOS Simulator SDK")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH YES)
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE NO)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES)

# Simulator doesn't need code signing
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO)

set(IOS_PLATFORM TRUE)
